# -*- coding: utf-8 -*-
"""CoFind-interfaces.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtWyk7t6tlaZbDIrg5UjqqsUYXh_MUrA
"""

# ===============================
# 1️⃣ تثبيت المكتبات اللازمة
# ===============================
!pip install --upgrade pip
!pip install inference --upgrade
!pip install supervision opencv-python-headless gradio

# ===============================
# 2️⃣ استدعاء المكتبات
# ===============================
import os, cv2
import supervision as sv
import inference
import gradio as gr

# ===============================
# 3️⃣ إعداد نموذج Roboflow
# ===============================
model_id = "coffee-beans-cofind-owops-qkb7f/4"  # عدلي لمشروعك ونسخته
api_key = "H3uNloapGePGyjUpHsqm"  # مفتاح Roboflow الخاص بك

# ===============================
# 4️⃣ تحميل النموذج من Roboflow Deploy
# ===============================
model = inference.get_model(model_id, api_key)

# ===============================
# 5️⃣ دالة لتشغيل التنبؤ وتحليل التوصية
# ===============================
def analyze_image(image):
    # عمل التنبؤ
    results = model.infer(image, confidence=0.4, overlap=30)[0]
    detections = sv.Detections.from_inference(results)

    # رسم الصناديق والتسميات
    box_annotator = sv.BoxAnnotator()
    label_annotator = sv.LabelAnnotator()
    annotated_image = box_annotator.annotate(scene=image, detections=detections)
    annotated_image = label_annotator.annotate(scene=annotated_image, detections=detections)

    # تحليل التوصية حسب Good أو Bad
    classes_detected = [det[0] for det in results]
    if "Good" in classes_detected:
        recommendation = "التوصية: الحبوب جيدة، يمكن التصدير أو الاستخدام العادي."
    else:
        recommendation = "التوصية: الحبوب سيئة، يُنصح باستخدامها بطرق بديلة لتقليل الهدر."

    return annotated_image, recommendation

# ===============================
# 6️⃣ إنشاء واجهة Gradio
# ===============================
iface = gr.Interface(
    fn=analyze_image,
    inputs=gr.Image(type="numpy"),
    outputs=[gr.Image(type="numpy"), gr.Textbox()],
    title="محلل جودة حبوب القهوة",
    description="ارفع صورة لحبوب القهوة لمعرفة التنبؤات وجودة الحبوب مع التوصيات."
)

# ===============================
# 7️⃣ تشغيل الواجهة
# ===============================
iface.launch()